name = "solidity-detector-file"
homepage = "https://hummanta.github.io/solidity-detector-file"
repository = "https://github.com/hummanta/solidity-detector-file"
language = "solidity"
kind = "detector"
description = "Detects Solidity files by verifying if any file in the specified path has a .sol extension."
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
latest = "v0.3.4"

[releases]
"v0.3.2" = "release-v0.3.2.toml"
"v0.2.0" = "release-v0.2.0.toml"
"v0.3.0" = "release-v0.3.0.toml"
"v0.3.1" = "release-v0.3.1.toml"
"v0.3.3" = "release-v0.3.3.toml"
"v0.1.0" = "release-v0.1.0.toml"
"v0.3.4" = "release-v0.3.4.toml"
