version = "v0.3.14"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.14/solidity-detector-file-v0.3.14-aarch64-unknown-linux-gnu.tar.gz"
hash = "6626dd0645b0a9fa0f2af74d75c94047e3985bd5aa6206b5b4eba25bf5efa024"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.14/solidity-detector-file-v0.3.14-aarch64-apple-darwin.tar.gz"
hash = "a8739d9f88055b9eac11514ddbb23fb44880af89e2d0db3d8293326236e61edd"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.14/solidity-detector-file-v0.3.14-x86_64-apple-darwin.tar.gz"
hash = "143d80d61ac3cc0e4475336dbf98c4bc1ca900c421dcc21e28751cacd5316f46"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.14/solidity-detector-file-v0.3.14-x86_64-pc-windows-msvc.tar.gz"
hash = "b264e9528fe761c922c04900c1e4082b31d10ab80935d6c7725b49810f11133d"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.14/solidity-detector-file-v0.3.14-x86_64-unknown-linux-gnu.tar.gz"
hash = "d18cb3402b75279436531eba3502a17114cf491f2c2672239db57220aeb4b9ce"
