version = "v0.3.13"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.13/solidity-detector-file-v0.3.13-aarch64-apple-darwin.tar.gz"
hash = "1e428431915eaa6d0e09ca86d46ed58d253a3a8165f78cc527efb69ba4217be0"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.13/solidity-detector-file-v0.3.13-aarch64-unknown-linux-gnu.tar.gz"
hash = "c9e97c8144c2a04b3e72c84eb4da9d29566ed2a0b85de46f6d5037707ec22829"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.13/solidity-detector-file-v0.3.13-x86_64-apple-darwin.tar.gz"
hash = "041087f0fd71ed96ccc323f09a9517321aed024e0ee9ce7801b8f5ad1bc2d763"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.13/solidity-detector-file-v0.3.13-x86_64-pc-windows-msvc.tar.gz"
hash = "abe0dc93b4a822a2bdb217de61d1901ff02a6744daa747a8714ff49f58ba7949"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.13/solidity-detector-file-v0.3.13-x86_64-unknown-linux-gnu.tar.gz"
hash = "108d0e9b118cacc3ae07225d51ad7c07edf88574163c1cc0b3f2ca2397a1e930"
