version = "v0.3.2"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.2/solidity-detector-file-v0.3.2-x86_64-unknown-linux-gnu.tar.gz"
hash = "a01515925d5ebf160c41c9d324480ce21a80cf4f586b3b98a4b0759d4d3c6e84"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.2/solidity-detector-file-v0.3.2-x86_64-apple-darwin.tar.gz"
hash = "f8efc5263a0a735a1bf44f7dd7b7f6d2732db7663606ee75e5fac24cab2fa600"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.2/solidity-detector-file-v0.3.2-aarch64-unknown-linux-gnu.tar.gz"
hash = "88c65cb383af4741f5b7a0c1acda0f0f231840ab692a87777d35cb3461876f14"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.2/solidity-detector-file-v0.3.2-x86_64-pc-windows-msvc.tar.gz"
hash = "3ab1009d5e36d7defd8f0a082a0a3e0ce25a75b3b8b017a39bdf585755e43b6f"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.2/solidity-detector-file-v0.3.2-aarch64-apple-darwin.tar.gz"
hash = "16fe7c1ac64ddbe746e76f002cf599c5a3ae618c94ae656fd917f29b26c58ad1"
