version = "v0.3.8"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.8/solidity-detector-file-v0.3.8-aarch64-apple-darwin.tar.gz"
hash = "634ef2c8e259708f0c42d10cf16ec7502b451813d7c46c79dc14d982218037c4"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.8/solidity-detector-file-v0.3.8-x86_64-pc-windows-msvc.tar.gz"
hash = "3a6ef9c286c6775a007698050e858e12eedb6766970a1252b29796e8a47ac169"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.8/solidity-detector-file-v0.3.8-x86_64-apple-darwin.tar.gz"
hash = "5dd3c651674014957aa9ffa22f1bbf4d607cc75da496ff67ef93c3721a2ec349"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.8/solidity-detector-file-v0.3.8-x86_64-unknown-linux-gnu.tar.gz"
hash = "e5eacdac869417c5c5a9c35fec9b642d0ef7a64eff592f84481235e3d409e447"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.8/solidity-detector-file-v0.3.8-aarch64-unknown-linux-gnu.tar.gz"
hash = "a87a647fcbb3fe3c2d59ba4807273a9fd47843760c0b1a2a195ddbb001ec7718"
