version = "v0.3.3"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.3/solidity-detector-file-v0.3.3-x86_64-unknown-linux-gnu.tar.gz"
hash = "8e7a824724cced35ecd924746f5f21c29f35d725555ff8515f09af3448a0bdd9"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.3/solidity-detector-file-v0.3.3-aarch64-apple-darwin.tar.gz"
hash = "b3d8f5f86651ad9905a5eb5b3372f08f7cfc1dced5f7e6e48905a0479cb59642"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.3/solidity-detector-file-v0.3.3-x86_64-apple-darwin.tar.gz"
hash = "68c6ba9bb487cf8fe50349a18764adcd4154f01eab44bb621dd88f575c8dbe65"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.3/solidity-detector-file-v0.3.3-aarch64-unknown-linux-gnu.tar.gz"
hash = "c0b1322e93e821ac9b738525005e8bfa0fe9397e876e26ba16c08a8777c49021"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.3/solidity-detector-file-v0.3.3-x86_64-pc-windows-msvc.tar.gz"
hash = "3c778ec26b48c9b5621496b8bd7821d8879939aa19ce308fb289006896bf5b9c"
