version = "v0.3.5"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.5/solidity-detector-file-v0.3.5-aarch64-unknown-linux-gnu.tar.gz"
hash = "d2c2db1086324a91da2bdf538399199a2a8f6e47a96f9cbd5de94347afb3dc52"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.5/solidity-detector-file-v0.3.5-x86_64-unknown-linux-gnu.tar.gz"
hash = "9ee2cc8b6016df21e78246fe6c642787742ad08186a87135c082d5f1e94d495c"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.5/solidity-detector-file-v0.3.5-aarch64-apple-darwin.tar.gz"
hash = "470f996ba5203b4bce8b635d377fa6e25e97ba14e1a5d128bf0d42b0ef5cc789"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.5/solidity-detector-file-v0.3.5-x86_64-apple-darwin.tar.gz"
hash = "212f544d45fd0a2bdb6f36d5433273ba9f266b7cac916469441b8675e2291caa"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.5/solidity-detector-file-v0.3.5-x86_64-pc-windows-msvc.tar.gz"
hash = "76242f3c3889e0a626398c263ad1b0b23e93d5f6d885033de62089e0723d6c83"
