version = "v0.3.11"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.11/solidity-detector-file-v0.3.11-aarch64-unknown-linux-gnu.tar.gz"
hash = "b2a06ce09ee59083a545d09df0688876bc62389d3175b1b2400f6ef8aa6ad0ea"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.11/solidity-detector-file-v0.3.11-aarch64-apple-darwin.tar.gz"
hash = "689750d0544a01eda86f0b51e6913cb4cdd205ac071e9c24409eabc40582be4d"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.11/solidity-detector-file-v0.3.11-x86_64-pc-windows-msvc.tar.gz"
hash = "d6f1a06663d2b818502cdbdefb56d20d1e965ea20b4e560d875f03a997a010b1"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.11/solidity-detector-file-v0.3.11-x86_64-apple-darwin.tar.gz"
hash = "51b4627a03e888b5a86183a701964cc9477a6d24072c51643b7e0da12c44c5f6"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.11/solidity-detector-file-v0.3.11-x86_64-unknown-linux-gnu.tar.gz"
hash = "fb4d0fe0ad13b453b8ad250f2b47168bfc6ad2971a683b6dbfb4a1b77c0ea04b"
