version = "v0.3.1"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.1/solidity-detector-file-v0.3.1-x86_64-unknown-linux-gnu.tar.gz"
hash = "3a4aa376ed749541e60a0235bf1dee269acc040f1b44cd6e80817d0e0cd937e8"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.1/solidity-detector-file-v0.3.1-aarch64-apple-darwin.tar.gz"
hash = "df8005712a741144df9143662456047196e7f68cfe1d7b6d87f2fb9c1ddd9f0e"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.1/solidity-detector-file-v0.3.1-x86_64-apple-darwin.tar.gz"
hash = "878ae3f6d5543751c978dbf1beafe0993dfe1c0accbf32eb51699fb1b5d5ab0d"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.1/solidity-detector-file-v0.3.1-x86_64-pc-windows-msvc.tar.gz"
hash = "e4644ddbc69cef891b5abcc1001188f1f1bfa3eb57d5a27cae5532ccf2fe2440"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.1/solidity-detector-file-v0.3.1-aarch64-unknown-linux-gnu.tar.gz"
hash = "4d8189cc34f61c06c2ebc7ab26eb36c297e482ee47bea98fd48675619d179031"
