version = "v0.3.9"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.9/solidity-detector-file-v0.3.9-x86_64-unknown-linux-gnu.tar.gz"
hash = "899bbe1f0d46625eec5c6f189b3ab43d2fca50217f2460ac76202e7936a1ac3a"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.9/solidity-detector-file-v0.3.9-aarch64-unknown-linux-gnu.tar.gz"
hash = "c112a8146e70612e490611b4cd413f31afdfea9092a30ba7cb0179394c7631ac"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.9/solidity-detector-file-v0.3.9-x86_64-pc-windows-msvc.tar.gz"
hash = "21bfe85a6fafbefb1ed63f133c19af3dce28b775315393af93f03f2fa25d3305"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.9/solidity-detector-file-v0.3.9-x86_64-apple-darwin.tar.gz"
hash = "9fb52ad4c79f735462e666d00b9c8fead7a8523f462d59f89e9e48d2d16e51a6"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.9/solidity-detector-file-v0.3.9-aarch64-apple-darwin.tar.gz"
hash = "a223685eb864bd122af23f628f17dbcebb01456abd37b3b7de0634d73940be27"
