version = "v0.3.12"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.12/solidity-detector-file-v0.3.12-x86_64-pc-windows-msvc.tar.gz"
hash = "96521016bec19ea83a388b229bb97377901035013bd833e4bf40e915718d9b51"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.12/solidity-detector-file-v0.3.12-x86_64-unknown-linux-gnu.tar.gz"
hash = "3e63c738dd1d9361467cba6afdb6b7d37c20270616957b00ef05b6e43d9c0c46"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.12/solidity-detector-file-v0.3.12-x86_64-apple-darwin.tar.gz"
hash = "ef217d4a586c981ec9e7d9e94a72a2bd9485d6cb9627d344d17176581d720cf9"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.12/solidity-detector-file-v0.3.12-aarch64-unknown-linux-gnu.tar.gz"
hash = "5860d0afdd661b94fa62883568d1086e2f87d0a1505470cba0514a01b534de26"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.12/solidity-detector-file-v0.3.12-aarch64-apple-darwin.tar.gz"
hash = "48f2586566a2e88b9a7d12bb96f637371910e7cab2a02f25824d67100eefc049"
