version = "v0.3.4"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.4/solidity-detector-file-v0.3.4-x86_64-apple-darwin.tar.gz"
hash = "7ffad40f13c54a8dc5d4f42e7e3dc3e59ef0f51ec5226106f6e14b8095cb2a5e"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.4/solidity-detector-file-v0.3.4-x86_64-unknown-linux-gnu.tar.gz"
hash = "5d40cf6798eb59116ee24ff3eac816298db17c198dccc91f6d1ba474f537f3a7"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.4/solidity-detector-file-v0.3.4-x86_64-pc-windows-msvc.tar.gz"
hash = "ee9e94f94b2601f20f4c396dde522a4f78a71d0bfcc932c9453a68d5fffd3443"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.4/solidity-detector-file-v0.3.4-aarch64-apple-darwin.tar.gz"
hash = "bbb6472346c5b460ac8993faf84dedc5e492ed2be8b0c9e5fa1f528a0d1dbe6d"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/solidity-detector-file/releases/download/v0.3.4/solidity-detector-file-v0.3.4-aarch64-unknown-linux-gnu.tar.gz"
hash = "d6021946657b6e34352c3f1bcc757e77a4f9a741fde108be300a001a7f4bcf76"
