name: Publish to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Release Binaries"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Checkout or create gh-pages branch
        run: |
          git fetch origin gh-pages 2>/dev/null
          git switch gh-pages 2>/dev/null || git switch --orphan gh-pages

      - name: Determine tag name
        id: tag
        run: |
          echo "Getting tag from workflow_run"
          echo "TAG_NAME=$(gh release view --json tagName --jq .tagName)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download checksums files
        uses: actions/download-artifact@v4
        with:
          path: manifests/
          pattern: "*-checksums"
          merge-multiple: true

      - name: Generate manifests
        run: just manifest false ${{ steps.tag.outputs.TAG_NAME }}

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add manifests/*
          git commit -m "Update manifests for ${{ steps.tag.outputs.TAG_NAME }}"
          git push origin gh-pages
